stages:
  - Test

.unit-test:
  stage: Test
  tags:
    - docker
  variables:
    REDIS_URL: 'redis'
    REDIS_PW: 'password'
    USE_ADDRESS_SANITIZER: 'YES'
    USE_THREAD_SANITIZER: 'YES'
  services:
  - name: redis:5
    alias: 'redis'
    command: ["redis-server", "--requirepass", "password"]
  script: |
    echo "Running unit tests with sanitizers: thread ($USE_THREAD_SANITIZER) and address ($USE_ADDRESS_SANITIZER)"

    SANITIZERS=()

    if [[ "$USE_THREAD_SANITIZER" == "YES" ]]
    then
      SANITIZERS+=("thread")
    fi

    if [[ "$USE_ADDRESS_SANITIZER" == "YES" ]]
    then
      SANITIZERS+=("address")
    fi

    if [[ 0 -eq ${#SANITIZERS[@]} ]]
    then
      SANITIZERS+=("")
    fi

    for SANITIZER in "${SANITIZERS[@]}"
    do
      SANITIZER_ARG=$([ -n SANITIZER ] && echo "--sanitize=$SANITIZER" || echo "")
      swift test $SANITIZER_ARG
    done
